name: "Release"

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version tag to use'     
        required: true


jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.event.inputs.release }}"
          prerelease: false
          title: "Release v${{ github.event.inputs.release }}"
